// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAv5kdcWiyA7VpeTvJ0VuUHZb7Y2G-3Ns',
    appId: '1:54232739648:web:0ee26920c0993bd15654a5',
    messagingSenderId: '54232739648',
    projectId: 'checkmate-aaabd',
    authDomain: 'checkmate-aaabd.firebaseapp.com',
    storageBucket: 'checkmate-aaabd.appspot.com',
    measurementId: 'G-KY8E1RKMDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsPnMETxHRHbZmtF7gOfIj3YT_22AuweE',
    appId: '1:54232739648:android:753c304282dc45f25654a5',
    messagingSenderId: '54232739648',
    projectId: 'checkmate-aaabd',
    storageBucket: 'checkmate-aaabd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb3yVJUoKQUNN4Geti9LujKHO9sE_j-R0',
    appId: '1:54232739648:ios:01574f23333b228a5654a5',
    messagingSenderId: '54232739648',
    projectId: 'checkmate-aaabd',
    storageBucket: 'checkmate-aaabd.appspot.com',
    iosBundleId: 'com.example.checkmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb3yVJUoKQUNN4Geti9LujKHO9sE_j-R0',
    appId: '1:54232739648:ios:ca7e30568e676bd75654a5',
    messagingSenderId: '54232739648',
    projectId: 'checkmate-aaabd',
    storageBucket: 'checkmate-aaabd.appspot.com',
    iosBundleId: 'com.example.checkmate.RunnerTests',
  );
}
